import './globals.css';

import Link from 'next/link';
// import dynamic from 'next/dynamic';
// import { Geist, Geist_Mono } from 'next/font/google';
import { Suspense } from 'react';

import Scene from '@/components/Scene/Scene';
import SceneManager from '@/components/SceneManager/SceneManager';
import Providers from '@/components/Providers/Providers';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
//   display: "swap",
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
//   display: "swap",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {  
  return (
    <html lang="en">
      <body>
        {/* levels navigation */}
        <nav>
          <Link href="?level=1">Level 1</Link>
          <Link href="?level=2">Level 2</Link>
        </nav>
        <Providers>
          { children }
          <Suspense fallback={<div>Loading...</div>}>
            <Scene>
              <SceneManager />
            </Scene>
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
